# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
    - none

pool: 
    vmImage: 'windows-latest'

variables:
    buildPlatform: 'Any CPU'
    buildConfiguration: 'release'
    solution: '**/MattProject.HammurabiGame.sln'
    project: '**/MattProject.HammurabiGame/csproj'

steps:
- task: NuGetToolInstaller@1
  name: 'NuGetToolInstaller'
  displayName: 'Nuget Tool Installer'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'HammurabiGame'
    publishLocation: 'Container'